### ISSUE TITLE
list index out of range on hardware check

### ISSUE THREAD

**Issue by Shadok** [daminoux43/check-vplex#2]
Hello,

On python 3.8, with "-m hardware", i got this error :
> Traceback (most recent call last):
>   File "./check_vplex.py", line 639, in <module>
>     main()
>   File "./check_vplex.py", line 623, in main
>     myvplex.get_hardware()
>   File "./check_vplex.py", line 479, in get_hardware
>     if status_split[1].lower().endswith('ok') and \

status_split only contains ['None']

**Comment by Shadok** [comment]
Other calls (frontend, io ...) work fine.

**Comment by Shadok** [comment]
For the record, a test with this script on the same vplex works well : https://github.com/schluo/check_mk_vplex_plugin
